### Call /model with explicit message
GET http://localhost:8080/model?message="Hello who are you my friend?"
Accept: text/plain

### Call /model using default message
GET http://localhost:8080/model
Accept: text/plain

### Call /groupchat using a dumb idea
GET http://localhost:8080/groupchat?message="I want to create my own jetpack for cats."
Accept: text/plain

### Call /research with a question
GET http://localhost:8080/research?message="How do magnets work?"
Accept: text/plain
